---
title: 灵魂拷问：什么是图
author: ''
date: '2019-05-30'
slug: www
categories: []
tags: []
---
```{r}
```


```{r}
library(ggplot2)
#load the data set
data(mtcars)
df <- mtcars[, c("mpg","cyl","wt")]
#将cyl转为因子型factor
df$cyl <- as.factor(df$cyl)
head(df)
 qplot(x=mpg, y=wt, data=df, geom = "point")

```


```{r}
library(ggplot2)
#load the data set
data(mtcars)
df <- mtcars[, c("mpg","cyl","wt")]
#将cyl转为因子型factor
df$cyl <- as.factor(df$cyl)
head(df)
 qplot(x=mpg, y=wt, data=df, geom = "point")
 qplot(x=mpg, y=wt, data = df, geom = c("point", "smooth"))
```
```{r}
qplot(x=mpg, y=wt, data = df, colour=cyl, shape=cyl)
```
```{r}
set.seed(1234)
wdata <- data.frame(
  sex=factor(rep(c("F", "M"), each=200)),
  weight=c(rnorm(200, 55), rnorm(200, 58))
)
head(wdata)
##   sex   weight
## 1   F 53.79293
## 2   F 55.27743
## 3   F 56.08444
## 4   F 52.65430
## 5   F 55.42912
## 6   F 55.50606
qplot(sex, weight, data = wdata, geom = "boxplot", fill=sex)
```
```{r}
wdata <-data.frame(sex=factor(rep(c("F","M"),each=200)),weight=c(rnorm(200,55),rnorm(200,58)))
a <- ggplot(wdata, aes(x=weight))
a
a+geom_area(stat = "bin",fill="red")
```

```{r}
head(diamonds)
library(ggplot2)

p1 <- ggplot(diamonds,aes(carat,price,colour=cut)) + 

      geom_point() + 

      theme(legend.position=c(0.9,0.72),

            legend.background=element_rect(I(0)))

p1

library(grid)

vie <- viewport(width=0.669,height=0.4,x=0.7,y=0.306)

p2 <- qplot(depth,data=diamonds,geom="density",xlim=c(54,70),fill=cut,alpha=I(0.2)) +

       theme(axis.text.y=element_text(face="bold",colour="black"),

             axis.title.y=element_blank(),

             axis.text.x=element_text(face="bold",colour="black"),

             plot.background=element_rect(I(0),linetype=0),

             panel.background=element_rect(I(0)),

             panel.grid.major=element_line(colour=NA),

             panel.grid.minor=element_line(colour=NA),

             legend.background=element_rect(I(0),linetype=1),

             legend.position=c(0.85,0.72))

print(p2,vp=vie)
```

```


